[book]
authors = ["Saket Sinha"]
language = "en"
multilingual = false
src = "src"
title = "Libre Car Control"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/disdi/proposal"
site-url = "https://saketsinha.de/proposal/"
