@startuml
json LibreCar {

   "SW": ["Application - Service to Signal Conversion", "Firmware -  HAL / device drivers"],

   "HW": ["Gateware- Soft RISC-V CPU vexriscv HDL", "FPGA - Lattice iCE40UP5k FPGA"]
}
@enduml
